### ISSUE TITLE
background is navy blue

### ISSUE THREAD

**Issue by macgruber99** [archSeer/colibri.vim#3]
I'm currently using Solarized and I already have "set background=dark".  But when I switched to Colibri, the background is now a navy blue, which I don't care for.

**Comment by archSeer** [comment]
Do you have "set termguicolor" enabled and use a terminal that supports 24 bit color (true color)?

There's a few test cases you can run at the start of this document: https://gist.github.com/XVilka/8346728

**Comment by macgruber99** [comment]
I have "set termguicolor"  enabled, but I get the following error: "E518: Unknown option: termguicolor".  I googled and found a thread that led me to believe it might be that the system vim installed on MacOS is 7.4 and that I should upgrade to 8.  I did that, but still getting the same error and still giving me the blue background.

**Comment by archSeer** [comment]
Ah sorry, it's plural, `set termguicolors`

**Comment by macgruber99** [comment]
Oh, and I'm using iTerm2 which supports true color.

**Comment by macgruber99** [comment]
I tried it with the 's', still giving me the same error.

**Comment by macgruber99** [comment]
OK, it's working now.  I changed it to plural _and_ made sure I was using Vim 8.

**Comment by archSeer** [comment]
Glad it's resolved!
